services:
  app:
    image: node:18-alpine3.15
    container_name: tipaton_react
    command: sh -c "cd /frontend && npm start"
    volumes:
      - .:/frontend
    working_dir: /frontend
    ports:
      - "3000:3000"
